// Seed ELA Unit 1 - Lessons 6-7
// Run: npx tsx prisma/seed-ela-u1-l6-l7.ts

import { config } from 'dotenv';
config({ path: '.env.local' });

import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('Seeding ELA Unit 1 - Lessons 6-7...');

  // LESSON 6: Revision & Voice
  const L6 = 'g6-ela-u1-l6';
  await prisma.lesson.update({ where: { id: L6 }, data: {
    subjectMode: 'ELA', externalUrl: null, estimatedMinutes: 45,
    learningGoal: 'Use revision strategies to strengthen writing. Apply power words, sentence variety, and show-don\'t-tell techniques to improve voice.',
    successCriteria: 'I can identify areas in my writing that need revision.\nI can use power words to replace weak language.\nI can vary my sentence structure for a stronger voice.',
    materials: 'Notebook, pencil, draft from Lesson 5',
    reflectionPrompt: 'How has your narrative changed from the first draft to now? What made the biggest difference?',
    warmUpConfig: { type: 'multiple_choice', prompt: 'Compare these two sentences. Which one has a STRONGER VOICE?\n\nA: "I was sad when I left."\nB: "A lump formed in my throat as I watched the front door shrink in the rearview mirror."', options: [{ label: 'Sentence A', value: 'a', correct: false }, { label: 'Sentence B', value: 'b', correct: true }] },
    masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false },
  }});
  await prisma.lessonBlock.deleteMany({ where: { lessonId: L6 } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: L6 } });

  const l6Blocks = [
    { id: 'ela-l6-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Revision Strategies</h3><p>Revision is not just fixing spelling -- it is about making your writing <strong>stronger</strong>, <strong>clearer</strong>, and more <strong>engaging</strong>.</p><h4>The ARMS Strategy</h4><ul><li><strong>A</strong>dd -- Add details, sensory language, or dialogue</li><li><strong>R</strong>emove -- Cut unnecessary words or repeated ideas</li><li><strong>M</strong>ove -- Reorganize sentences or paragraphs for better flow</li><li><strong>S</strong>ubstitute -- Replace weak words with power words</li></ul>' } },
    { id: 'ela-l6-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Power Words: Upgrade Your Language</h3><p>Power words are specific, vivid words that replace vague or overused language.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:16px 0"><div style="background:#fee2e2;padding:10px;border-radius:6px;text-align:center"><strong>Weak:</strong> walked</div><div style="background:#dcfce7;padding:10px;border-radius:6px;text-align:center"><strong>Power:</strong> shuffled, strutted, crept, marched</div><div style="background:#fee2e2;padding:10px;border-radius:6px;text-align:center"><strong>Weak:</strong> said</div><div style="background:#dcfce7;padding:10px;border-radius:6px;text-align:center"><strong>Power:</strong> whispered, announced, stammered, pleaded</div><div style="background:#fee2e2;padding:10px;border-radius:6px;text-align:center"><strong>Weak:</strong> nice</div><div style="background:#dcfce7;padding:10px;border-radius:6px;text-align:center"><strong>Power:</strong> gracious, welcoming, radiant, genuine</div><div style="background:#fee2e2;padding:10px;border-radius:6px;text-align:center"><strong>Weak:</strong> big</div><div style="background:#dcfce7;padding:10px;border-radius:6px;text-align:center"><strong>Power:</strong> enormous, towering, sprawling, immense</div></div>' } },
    { id: 'ela-l6-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Sentence Variety: Mix It Up</h3><p>Strong writers vary their sentence lengths and structures. Compare:</p><div style="background:#fee2e2;padding:12px;border-radius:8px;margin:8px 0"><strong>Monotonous:</strong> "I walked to school. I saw my friend. I said hello. We went to class."</div><div style="background:#dcfce7;padding:12px;border-radius:8px;margin:8px 0"><strong>Varied:</strong> "As I rounded the corner to school, I spotted Maya waiting by the big oak tree. \'You are late again!\' she laughed, linking her arm through mine. Together, we rushed through the double doors just as the bell rang."</div><p style="margin-top:12px">Techniques for variety:</p><ul><li>Start with a <strong>prepositional phrase</strong>: "Under the flickering lights..."</li><li>Start with an <strong>-ing word</strong>: "Clutching my backpack..."</li><li>Use a <strong>short sentence for impact</strong>: "She was gone."</li><li>Combine short sentences with <strong>conjunctions</strong>: "I wanted to speak, but the words stuck."</li></ul>' } },
    { id: 'ela-l6-learn-4', section: 'LEARN', blockType: 'VOCABULARY', order: 4, content: { terms: [{ term: 'Revision', definition: 'The process of improving writing by adding, removing, moving, or substituting content.', example: 'During revision, she added sensory details to make the scene more vivid.' }, { term: 'Power Words', definition: 'Specific, vivid words that replace weak or overused language.', example: 'Instead of "walked," she wrote "crept" to show caution.' }, { term: 'Sentence Variety', definition: 'Using different sentence lengths and structures to create rhythm and keep readers engaged.', example: 'Mixing short and long sentences creates a natural flow.' }, { term: 'Voice', definition: 'The unique personality and style that comes through in a writer\'s words.', example: 'Her voice was warm and funny -- you could hear her personality in every line.' }] } },
    { id: 'ela-l6-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Power Word Upgrade: Rewrite each sentence by replacing the underlined weak word with a power word.\n\n1. She WALKED across the stage. -> She _____ across the stage.\n2. "I am going," he SAID quietly. -> "I am going," he _____ quietly.\n3. The room was BIG. -> The room was _____.\n4. The food smelled GOOD. -> The food smelled _____.\n5. He felt BAD about what happened. -> He felt _____ about what happened.', minLength: 20, rubricHint: 'Replaces all 5 weak words with specific, vivid alternatives. Power words match the context.' } },
    { id: 'ela-l6-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Take your draft opening paragraph from Lesson 5 (or write a new one) and revise it using the ARMS strategy:\n\n1. ADD at least one sensory detail\n2. REMOVE at least one unnecessary word or phrase\n3. MOVE at least one sentence for better flow (or explain why the order is already strong)\n4. SUBSTITUTE at least two weak words with power words\n\nWrite your revised paragraph below, then explain what you changed and why.', minLength: 50, rubricHint: 'Shows clear evidence of all 4 ARMS revisions. Revised version is stronger than original. Explains revision choices.' } },
    { id: 'ela-l6-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How has your narrative changed from the first draft to now? What revision strategy made the biggest difference? What would you still like to improve?', minLength: 30, rubricHint: 'Compares before and after. Names specific revision strategies used. Sets a revision goal.' } },
  ];

  for (const b of l6Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L6, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }

  const l6Questions = [
    { id: 'ela-l6-q1', questionText: 'What does the "S" in the ARMS revision strategy stand for?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Spell-check', value: 'a' }, { label: 'Substitute -- replace weak words with stronger ones', value: 'b', correct: true }, { label: 'Summarize', value: 'c' }, { label: 'Simplify', value: 'd' }], correctAnswer: 'b', explanation: 'ARMS stands for Add, Remove, Move, Substitute. The S means substituting weak or vague words with more specific, vivid power words.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l6-q2', questionText: 'Which is a POWER WORD replacement for "said"?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'told', value: 'a' }, { label: 'stammered', value: 'b', correct: true }, { label: 'talked', value: 'c' }, { label: 'went', value: 'd' }], correctAnswer: 'b', explanation: '"Stammered" is a power word because it is specific -- it tells us HOW the person spoke (nervously, with difficulty). "Told" and "talked" are still vague.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l6-q3', questionText: '"Clutching my backpack, I raced through the doors." This sentence begins with:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A prepositional phrase', value: 'a' }, { label: 'A participial phrase (an -ing phrase)', value: 'b', correct: true }, { label: 'A conjunction', value: 'c' }, { label: 'A question', value: 'd' }], correctAnswer: 'b', explanation: '"Clutching my backpack" is a participial phrase -- it starts with a present participle (-ing verb) and adds detail about the action.', outcomeCode: 'ELA.6.4', difficulty: 2 },
    { id: 'ela-l6-q4', questionText: 'Why is SENTENCE VARIETY important in writing?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It makes the writing longer', value: 'a' }, { label: 'It creates rhythm and keeps readers engaged', value: 'b', correct: true }, { label: 'It shows you know many words', value: 'c' }, { label: 'It is required by grammar rules', value: 'd' }], correctAnswer: 'b', explanation: 'Mixing short and long sentences creates a natural rhythm that keeps readers engaged. Monotonous sentence patterns bore readers.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l6-q5', questionText: '"She was gone." This is an example of a SHORT SENTENCE used for:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Filling space', value: 'a' }, { label: 'Dramatic impact and emphasis', value: 'b', correct: true }, { label: 'Introducing a character', value: 'c' }, { label: 'Explaining a concept', value: 'd' }], correctAnswer: 'b', explanation: 'Writers use short sentences deliberately for dramatic impact. After longer, descriptive sentences, a short sentence creates a powerful pause.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l6-q6', questionText: 'Which sentence uses an APOSTROPHE correctly?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'The dogs\' ran fast. (one dog)', value: 'a' }, { label: 'The dog\'s tail wagged.', value: 'b', correct: true }, { label: 'The dogs are play\'ing.', value: 'c' }, { label: 'It\'s bowl was empty. (the bowl belonging to the dog)', value: 'd' }], correctAnswer: 'b', explanation: '"Dog\'s tail" correctly uses an apostrophe to show possession -- the tail belonging to the dog. Option D is wrong because "its" (possessive) does not need an apostrophe.', outcomeCode: 'ELA.6.4', difficulty: 2 },
    { id: 'ela-l6-q7', questionText: '"A lump formed in my throat." This is an example of:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Telling', value: 'a' }, { label: 'Showing -- using a physical detail to convey emotion', value: 'b', correct: true }, { label: 'Neither showing nor telling', value: 'c' }, { label: 'A fact', value: 'd' }], correctAnswer: 'b', explanation: 'This is showing -- instead of saying "I was sad," the writer uses a physical sensation (lump in throat) that lets the reader FEEL the emotion.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l6-q8', questionText: 'Which sentence demonstrates correct subject-verb AGREEMENT?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'The students in the class was excited.', value: 'a' }, { label: 'The students in the class were excited.', value: 'b', correct: true }, { label: 'The students in the class are was excited.', value: 'c' }, { label: 'The student in the class were excited.', value: 'd' }], correctAnswer: 'b', explanation: 'The subject "students" is plural, so it needs the plural verb "were." Don\'t be tricked by the prepositional phrase "in the class" between the subject and verb.', outcomeCode: 'ELA.6.4', difficulty: 2 },
  ];

  for (const q of l6Questions) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L6, questionText: q.questionText, questionType: q.questionType, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L6: ' + l6Blocks.length + ' blocks, ' + l6Questions.length + ' questions');

  // LESSON 7: Discussion Circle
  const L7 = 'g6-ela-u1-l7';
  await prisma.lesson.update({ where: { id: L7 }, data: {
    subjectMode: 'ELA', externalUrl: null, estimatedMinutes: 40,
    learningGoal: 'Practice active listening and respectful discussion skills. Share a personal narrative excerpt and provide constructive feedback. Reflect on unit learning.',
    successCriteria: 'I can listen actively and respond respectfully to peers.\nI can share my writing with confidence.\nI can provide constructive feedback using sentence stems.\nI can reflect on my growth throughout the unit.',
    materials: 'Notebook, pencil, revised narrative from Lesson 6',
    reflectionPrompt: 'What is the most important thing you learned about yourself through this unit?',
    warmUpConfig: { type: 'constructed_response', prompt: 'Think about the BEST listener you know. What makes them a good listener?\n\nName 2-3 things good listeners DO when someone is sharing.' },
    masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false },
  }});
  await prisma.lessonBlock.deleteMany({ where: { lessonId: L7 } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: L7 } });

  const l7Blocks = [
    { id: 'ela-l7-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Active Listening Skills</h3><p>In a discussion circle, listening is just as important as speaking. Active listening means you are fully focused on the speaker.</p><h4>What Active Listeners Do:</h4><ul><li>Make eye contact (or face the speaker)</li><li>Put away distractions</li><li>Nod or show they are following along</li><li>Wait for the speaker to finish before responding</li><li>Ask follow-up questions</li><li>Connect to something the speaker said before adding their own ideas</li></ul>' } },
    { id: 'ela-l7-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Discussion Sentence Stems</h3><p>Use these sentence stems to share your thoughts respectfully and build on what others say:</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:16px 0"><div style="background:#dbeafe;padding:10px;border-radius:6px"><strong>To share:</strong><br>"In my narrative, I wrote about..."<br>"Something important to my identity is..."<br>"I chose to focus on... because..."</div><div style="background:#fef3c7;padding:10px;border-radius:6px"><strong>To respond:</strong><br>"I noticed that your writing..."<br>"I connected with your story when..."<br>"Something I admire about your narrative is..."</div><div style="background:#dcfce7;padding:10px;border-radius:6px"><strong>To build on:</strong><br>"Adding to what you said..."<br>"That reminds me of..."<br>"I agree because..."</div><div style="background:#fce7f3;padding:10px;border-radius:6px"><strong>To give feedback:</strong><br>"One thing that was really strong was..."<br>"I wonder if you could add..."<br>"A detail that stood out to me was..."</div></div>' } },
    { id: 'ela-l7-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Constructive Feedback</h3><p>Good feedback is specific, kind, and helpful. It names what is working and suggests what could be even stronger.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:16px 0"><div style="background:#fee2e2;padding:10px;border-radius:6px"><strong>Unhelpful:</strong> "It was good." / "I liked it."</div><div style="background:#dcfce7;padding:10px;border-radius:6px"><strong>Helpful:</strong> "Your opening hook grabbed my attention because you started with dialogue. I could picture the scene when you described the smell of your grandmother\'s kitchen."</div></div><p>The formula: <strong>Name what works + Be specific + Suggest one thing to try</strong></p>' } },
    { id: 'ela-l7-learn-4', section: 'LEARN', blockType: 'VOCABULARY', order: 4, content: { terms: [{ term: 'Active Listening', definition: 'Fully focusing on the speaker, showing you are engaged, and responding thoughtfully.', example: 'She practiced active listening by making eye contact and asking a follow-up question.' }, { term: 'Constructive Feedback', definition: 'Specific, kind, and helpful comments that name strengths and suggest improvements.', example: '"Your dialogue felt real. Maybe you could add more sensory details in the climax."' }, { term: 'Discussion Circle', definition: 'A structured conversation where participants take turns sharing and responding to each other respectfully.', example: 'In our discussion circle, each student shared their narrative excerpt.' }, { term: 'Sentence Stems', definition: 'Starter phrases that help you structure your responses in a discussion.', example: '"I connected with your story when..." is a sentence stem.' }] } },
    { id: 'ela-l7-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Prepare to share your narrative. Choose your STRONGEST paragraph or excerpt (4-8 sentences) and write it below.\n\nBefore sharing, review your excerpt and check:\n- Does it use show-don\'t-tell?\n- Does it have a clear voice?\n- Would a listener be able to picture the scene?', minLength: 30, rubricHint: 'Selects a strong excerpt. Writing shows revision strategies from L5-L6. Excerpt has voice and sensory details.' } },
    { id: 'ela-l7-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'After listening to (or reading) a classmate\'s narrative excerpt, write constructive feedback using this format:\n\n1. One thing that was really strong: ___\n2. A detail that stood out to me: ___\n3. Something I connected with: ___\n4. One suggestion to make it even stronger: ___\n\n(If working independently, give this feedback to your OWN narrative from the perspective of a reader.)', minLength: 30, rubricHint: 'Uses the feedback format. Comments are specific, not vague. Gives both praise and a constructive suggestion.' } },
    { id: 'ela-l7-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Unit 1 Final Reflection:\n\n1. What is the most important thing you learned about yourself through this unit?\n2. How has your understanding of identity changed since Lesson 1?\n3. Which skill grew the most: comprehension, vocabulary, theme analysis, narrative writing, or discussion? Why?\n4. Look back at your Lesson 1 warm-up (what your name means). Would you add anything now?', minLength: 40, rubricHint: 'Reflects on personal growth across the unit. References specific lessons or skills. Shows metacognition about learning process.' } },
  ];

  for (const b of l7Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L7, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }

  const l7Questions = [
    { id: 'ela-l7-q1', questionText: 'Which is an example of ACTIVE LISTENING?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Looking at your phone while someone talks', value: 'a' }, { label: 'Waiting for the speaker to finish, then asking a follow-up question', value: 'b', correct: true }, { label: 'Interrupting to share your own story', value: 'c' }, { label: 'Thinking about what you will say next instead of listening', value: 'd' }], correctAnswer: 'b', explanation: 'Active listening means fully engaging with the speaker -- waiting patiently, then responding thoughtfully. Interrupting or being distracted are the opposite.', outcomeCode: 'ELA.6.5', difficulty: 1 },
    { id: 'ela-l7-q2', questionText: 'Which feedback is CONSTRUCTIVE (specific and helpful)?', questionType: 'MULTIPLE_CHOICE', options: [{ label: '"It was good."', value: 'a' }, { label: '"Your opening hook grabbed my attention because you started with dialogue."', value: 'b', correct: true }, { label: '"I liked it."', value: 'c' }, { label: '"Nice job."', value: 'd' }], correctAnswer: 'b', explanation: 'Constructive feedback is SPECIFIC -- it names exactly what worked ("opening hook," "started with dialogue") and explains WHY. Vague praise like "good" or "nice" is not helpful.', outcomeCode: 'ELA.6.5', difficulty: 1 },
    { id: 'ela-l7-q3', questionText: '"I connected with your story when you described feeling out of place." This is an example of a:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Run-on sentence', value: 'a' }, { label: 'Complex sentence with a dependent clause', value: 'b', correct: true }, { label: 'Simple sentence', value: 'c' }, { label: 'Fragment', value: 'd' }], correctAnswer: 'b', explanation: '"When you described feeling out of place" is a dependent clause -- it cannot stand alone as a sentence. It is attached to the independent clause to form a complex sentence.', outcomeCode: 'ELA.6.5', difficulty: 2 },
    { id: 'ela-l7-q4', questionText: 'A SENTENCE STEM is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'The last word of a sentence', value: 'a' }, { label: 'A starter phrase that helps you structure your response', value: 'b', correct: true }, { label: 'A type of punctuation', value: 'c' }, { label: 'A grammatical error', value: 'd' }], correctAnswer: 'b', explanation: 'Sentence stems are starter phrases like "I connected with..." or "Adding to what you said..." that help structure thoughtful discussion responses.', outcomeCode: 'ELA.6.5', difficulty: 1 },
    { id: 'ela-l7-q5', questionText: 'Which word in this sentence is a CONJUNCTION? "I wanted to speak, but the words stuck."', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'wanted', value: 'a' }, { label: 'speak', value: 'b' }, { label: 'but', value: 'c', correct: true }, { label: 'stuck', value: 'd' }], correctAnswer: 'c', explanation: '"But" is a coordinating conjunction (FANBOYS: For, And, Nor, But, Or, Yet, So). It connects two independent clauses in this compound sentence.', outcomeCode: 'ELA.6.5', difficulty: 1 },
    { id: 'ela-l7-q6', questionText: 'In a discussion, "building on" what someone said means:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Changing the topic completely', value: 'a' }, { label: 'Connecting your idea to what they shared and adding to it', value: 'b', correct: true }, { label: 'Repeating exactly what they said', value: 'c' }, { label: 'Disagreeing with everything', value: 'd' }], correctAnswer: 'b', explanation: 'Building on means connecting to the previous speaker\'s idea and extending it with your own related thoughts, using stems like "Adding to what you said..."', outcomeCode: 'ELA.6.5', difficulty: 1 },
    { id: 'ela-l7-q7', questionText: 'Which sentence is a FRAGMENT (incomplete sentence)?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'She shared her narrative with confidence.', value: 'a' }, { label: 'Because she wanted to be heard.', value: 'b', correct: true }, { label: 'The class listened carefully.', value: 'c' }, { label: 'Everyone clapped when she finished.', value: 'd' }], correctAnswer: 'b', explanation: '"Because she wanted to be heard" starts with a subordinating conjunction and has no independent clause -- it is a dependent clause fragment. It needs to be attached to a main clause.', outcomeCode: 'ELA.6.5', difficulty: 2 },
    { id: 'ela-l7-q8', questionText: 'Reviewing this entire unit, which is the correct order of the PLOT DIAGRAM?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Climax, Exposition, Resolution, Rising Action, Falling Action', value: 'a' }, { label: 'Exposition, Rising Action, Climax, Falling Action, Resolution', value: 'b', correct: true }, { label: 'Resolution, Falling Action, Climax, Rising Action, Exposition', value: 'c' }, { label: 'Rising Action, Falling Action, Climax, Exposition, Resolution', value: 'd' }], correctAnswer: 'b', explanation: 'The plot diagram follows this order: Exposition (intro) -> Rising Action (tension builds) -> Climax (turning point) -> Falling Action (settling) -> Resolution (ending). This is a retrieval question from Lesson 4!', outcomeCode: 'ELA.6.3', difficulty: 1 },
  ];

  for (const q of l7Questions) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L7, questionText: q.questionText, questionType: q.questionType, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L7: ' + l7Blocks.length + ' blocks, ' + l7Questions.length + ' questions');

  console.log('\nELA Unit 1 Lessons 6-7 seeded!');
}

main()
  .catch((e) => { console.error('Seed failed:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
