// Seed ELA Unit 1 - Lessons 3-5
// Run: npx tsx prisma/seed-ela-u1-l3-l5.ts

import { config } from 'dotenv';
config({ path: '.env.local' });

import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('Seeding ELA Unit 1 - Lessons 3-5...');

  // LESSON 3: Theme & Message
  const L3 = 'g6-ela-u1-l3';
  await prisma.lesson.update({ where: { id: L3 }, data: {
    subjectMode: 'ELA', externalUrl: null, estimatedMinutes: 40,
    learningGoal: 'Explain the difference between theme and topic. Identify the theme of a text about identity. Support a theme statement with evidence from the text.',
    successCriteria: 'I can explain the difference between theme and topic.\nI can identify the theme of a text about identity.\nI can support my theme statement with evidence from the text.',
    materials: 'Notebook, pencil',
    reflectionPrompt: 'What is a theme from your own life -- a lesson you have learned about identity or belonging?',
    warmUpConfig: { type: 'constructed_response', prompt: 'Think about a movie or book you love.\n\nWhat was the TOPIC (what it was about, in 1-2 words)?\nWhat was the MESSAGE (what it taught you)?' },
    masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false },
  }});
  await prisma.lessonBlock.deleteMany({ where: { lessonId: L3 } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: L3 } });

  const l3Blocks = [
    { id: 'ela-l3-learn-1', section: 'LEARN', blockType: 'VIDEO', order: 1, content: { url: 'https://www.youtube.com/embed/VoiaAr9y35s', title: 'Theme vs. Topic (4 min)', transcript: 'Learn the difference between theme and topic in literature.', aiSummary: 'A topic is what a text is about in 1-2 words (e.g., identity). A theme is the deeper message the author communicates about the topic, stated as a full sentence (e.g., "Embracing your true identity takes courage but leads to belonging"). Themes are universal lessons that apply across stories and cultures.' } },
    { id: 'ela-l3-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Topic vs. Theme -- What is the Difference?</h3><ul><li><strong>Topic:</strong> What the text is about, in 1-2 words. Example: <em>identity</em></li><li><strong>Theme:</strong> The deeper message the author is teaching. Example: <em>"Embracing your true identity takes courage but leads to belonging."</em></li></ul><p>A topic can be stated in a word. A theme must be a complete sentence that captures the lesson or message.</p>' } },
    { id: 'ela-l3-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Re-read: "The Name Jar" Excerpt</h3><blockquote style="border-left:3px solid #e85d9a;padding:12px 16px;margin:12px 0;font-style:italic;color:#475569">"Unhei stared at the name tag on her desk. On the bus, the other kids had stumbled over her name, laughing. She wanted to disappear. But her grandmother\'s voice echoed: <em>\'Your name means grace. It was chosen with love.\'</em> The next day, Unhei stood up and said her name clearly. The class practiced until they got it right."</blockquote><div style="display:flex;gap:12px;margin-top:16px"><div style="flex:1;background:#f1f5f9;padding:12px;border-radius:8px"><strong>Topic:</strong> Identity, names, belonging</div><div style="flex:1;background:#f1f5f9;padding:12px;border-radius:8px"><strong>Theme:</strong> "When you embrace who you are, others learn to respect you too."</div></div>' } },
    { id: 'ela-l3-learn-4', section: 'LEARN', blockType: 'VOCABULARY', order: 4, content: { terms: [{ term: 'Topic', definition: 'The subject a text is about -- can be stated in 1-2 words (e.g., "identity," "friendship").', example: 'The topic of "The Name Jar" is identity and names.' }, { term: 'Theme', definition: 'The deeper message or lesson the author communicates about the topic -- stated as a full sentence.', example: '"When you embrace who you are, others learn to respect you too."' }, { term: 'Universal Theme', definition: 'A theme that applies across cultures and time periods.', example: '"True strength comes from being yourself" is a universal theme.' }] } },
    { id: 'ela-l3-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Read each statement and decide: is it a THEME (a message/lesson) or a TOPIC (a subject)?', pairs: [{ left: 'Identity', right: 'Topic' }, { left: 'Embracing your culture makes you stronger', right: 'Theme' }, { left: 'Friendship', right: 'Topic' }, { left: 'True friends accept you for who you are', right: 'Theme' }, { left: 'Courage', right: 'Topic' }, { left: 'Standing up for yourself is hard but worth it', right: 'Theme' }] } },
    { id: 'ela-l3-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Read this passage and identify the theme:\n\n"Amara\'s parents spoke Somali at home, but at school she only spoke English. She used to pretend she did not understand Somali when friends were around. Then one day, her younger brother asked her to read him a Somali bedtime story. Hearing the words aloud, she felt something warm -- like finding a piece of herself she had hidden away."\n\nWhat is the TOPIC of this passage? (1-2 words)\nWhat is the THEME? (Write as a complete sentence)\nWhat text clues helped you identify the theme?', minLength: 30, rubricHint: 'Correctly distinguishes topic from theme. States theme as a full sentence. Cites text evidence.' } },
    { id: 'ela-l3-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What is a theme from your own life -- a lesson you have learned about identity or belonging? Write it as a complete sentence, then explain what experience taught you that lesson.', minLength: 30, rubricHint: 'States a personal theme as a complete sentence. Connects to a real experience. Shows reflection on identity.' } },
  ];

  for (const b of l3Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L3, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }

  const l3Questions = [
    { id: 'ela-l3-q1', questionText: 'What is the difference between TOPIC and THEME?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Topic is the title; theme is the summary', value: 'a' }, { label: 'Topic is the subject (1-2 words); theme is the deeper message (full sentence)', value: 'b', correct: true }, { label: 'Topic is for fiction; theme is for nonfiction', value: 'c' }, { label: 'They mean the same thing', value: 'd' }], correctAnswer: 'b', explanation: 'A topic names the subject in 1-2 words. A theme states the author\'s deeper message as a complete sentence.', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l3-q2', questionText: 'Which of these is a THEME (not a topic)?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Friendship', value: 'a' }, { label: 'Courage', value: 'b' }, { label: 'True friends accept you even when you are different', value: 'c', correct: true }, { label: 'Identity', value: 'd' }], correctAnswer: 'c', explanation: 'A theme must be a complete sentence that states a message or lesson. The other options are topics -- single words naming a subject.', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l3-q3', questionText: '"When you embrace who you are, others learn to respect you too." This is an example of a COMPOUND sentence because it:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Has one subject and one verb', value: 'a' }, { label: 'Contains two independent clauses joined by a comma and conjunction', value: 'b', correct: true }, { label: 'Starts with "when"', value: 'c' }, { label: 'Is very long', value: 'd' }], correctAnswer: 'b', explanation: 'A compound sentence joins two independent clauses (complete thoughts) with a comma and a coordinating conjunction. Here: "When you embrace who you are" + "others learn to respect you too."', outcomeCode: 'ELA.6.3', difficulty: 2 },
    { id: 'ela-l3-q4', questionText: '"She felt something warm -- like finding a piece of herself she had hidden away." This sentence contains:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A metaphor', value: 'a' }, { label: 'A simile', value: 'b', correct: true }, { label: 'Onomatopoeia', value: 'c' }, { label: 'Alliteration', value: 'd' }], correctAnswer: 'b', explanation: 'The word "like" signals a comparison: feeling warm is compared to finding a hidden piece of herself. That makes it a simile.', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l3-q5', questionText: 'A UNIVERSAL THEME is one that:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Only appears in one specific story', value: 'a' }, { label: 'Applies across cultures and time periods', value: 'b', correct: true }, { label: 'Is always about space or the universe', value: 'c' }, { label: 'Is stated directly by the author', value: 'd' }], correctAnswer: 'b', explanation: 'Universal themes are lessons that resonate across cultures, countries, and centuries -- like "being yourself takes courage" or "belonging matters."', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l3-q6', questionText: 'In the sentence "Unhei stood up and said her name clearly," the ADVERB is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'stood', value: 'a' }, { label: 'up', value: 'b' }, { label: 'clearly', value: 'c', correct: true }, { label: 'name', value: 'd' }], correctAnswer: 'c', explanation: '"Clearly" is an adverb -- it describes HOW she said her name. Adverbs modify verbs and often end in -ly.', outcomeCode: 'ELA.6.3', difficulty: 2 },
    { id: 'ela-l3-q7', questionText: 'Which punctuation mark is used to introduce a list or explanation?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Semicolon (;)', value: 'a' }, { label: 'Colon (:)', value: 'b', correct: true }, { label: 'Comma (,)', value: 'c' }, { label: 'Period (.)', value: 'd' }], correctAnswer: 'b', explanation: 'A colon introduces what follows -- a list, explanation, or example. Like this: identity, belonging, and culture.', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l3-q8', questionText: '"The class practiced until they got it right." The word "practiced" is in which verb tense?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Present tense', value: 'a' }, { label: 'Past tense', value: 'b', correct: true }, { label: 'Future tense', value: 'c' }, { label: 'Present progressive', value: 'd' }], correctAnswer: 'b', explanation: '"Practiced" uses the -ed ending, which signals past tense -- the action already happened.', outcomeCode: 'ELA.6.3', difficulty: 1 },
  ];

  for (const q of l3Questions) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L3, questionText: q.questionText, questionType: q.questionType, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L3: ' + l3Blocks.length + ' blocks, ' + l3Questions.length + ' questions');

  // LESSON 4: Narrative Structure
  const L4 = 'g6-ela-u1-l4';
  await prisma.lesson.update({ where: { id: L4 }, data: {
    subjectMode: 'ELA', externalUrl: null, estimatedMinutes: 40,
    learningGoal: 'Identify the 5 parts of a plot diagram. Map a narrative onto a plot structure. Explain how structure creates tension and meaning.',
    successCriteria: 'I can identify the 5 parts of a plot diagram.\nI can map a narrative onto a plot structure.\nI can explain how structure creates tension and meaning.',
    materials: 'Notebook, pencil',
    reflectionPrompt: 'Why do you think most stories follow a similar structure? Does it help or limit storytelling?',
    warmUpConfig: { type: 'constructed_response', prompt: 'Think of a story you know well (book, movie, fairy tale).\n\nCan you name THE PROBLEM (conflict) and THE MOST INTENSE MOMENT (climax)?' },
    masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false },
  }});
  await prisma.lessonBlock.deleteMany({ where: { lessonId: L4 } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: L4 } });

  const l4Blocks = [
    { id: 'ela-l4-learn-1', section: 'LEARN', blockType: 'VIDEO', order: 1, content: { url: 'https://www.youtube.com/embed/Rez1-4ItsPc', title: 'Plot Diagram (5 min)', transcript: 'Learn the 5 parts of a plot diagram and how stories are structured.', aiSummary: 'Every story follows a structure: Exposition (introduction), Rising Action (tension builds), Climax (turning point), Falling Action (conflict settles), Resolution (ending). Understanding this structure helps readers analyze how authors create meaning and tension.' } },
    { id: 'ela-l4-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>The 5 Parts of a Plot Diagram</h3><ol><li><strong>Exposition:</strong> Meet the characters and setting. Everything is "normal."</li><li><strong>Rising Action:</strong> Problems build. Tension increases.</li><li><strong>Climax:</strong> The turning point -- the biggest moment of tension.</li><li><strong>Falling Action:</strong> The conflict begins to settle.</li><li><strong>Resolution:</strong> The story ends. What has changed?</li></ol>' } },
    { id: 'ela-l4-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Anchor Text: "The Name Jar" -- Plot Map</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px"><div style="background:#f1f5f9;padding:12px;border-radius:8px"><strong>1. Exposition</strong><br>Unhei arrives at a new school. Kids struggle with her name.</div><div style="background:#f1f5f9;padding:12px;border-radius:8px"><strong>2. Rising Action</strong><br>She considers choosing an American name. Classmates put suggestions in a jar.</div><div style="background:#f1f5f9;padding:12px;border-radius:8px"><strong>3. Climax</strong><br>Unhei decides to keep her real name and tells the class what it means.</div><div style="background:#f1f5f9;padding:12px;border-radius:8px"><strong>4. Falling Action</strong><br>Classmates practice saying her name correctly.</div><div style="background:#f1f5f9;padding:12px;border-radius:8px;grid-column:span 2"><strong>5. Resolution</strong><br>Unhei feels proud and accepted. She belongs as herself.</div></div>' } },
    { id: 'ela-l4-learn-4', section: 'LEARN', blockType: 'VOCABULARY', order: 4, content: { terms: [{ term: 'Exposition', definition: 'The beginning -- introduces characters, setting, and the situation before the conflict.', example: 'Unhei arrives at a new school.' }, { term: 'Rising Action', definition: 'Events that build tension and develop the conflict.', example: 'She considers changing her name.' }, { term: 'Climax', definition: 'The turning point -- the moment of greatest tension or the key decision.', example: 'Unhei decides to keep her real name.' }, { term: 'Falling Action', definition: 'Events after the climax as the conflict starts to resolve.', example: 'Classmates practice saying her name.' }, { term: 'Resolution', definition: 'The ending -- how the story wraps up and what has changed.', example: 'Unhei feels proud and accepted.' }] } },
    { id: 'ela-l4-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each event from Kai\'s story to the correct part of the plot diagram:\n\n"Kai moved to a new city and started at a school where nobody looked like him. He tried to fit in by copying how other kids dressed and talked. When a class project asked him to present his culture, he almost lied. But he decided to share the truth -- his Indigenous heritage, the powwow dances, the beadwork. The class was amazed. Kai finally felt seen."', pairs: [{ left: 'Kai moved to a new city and started school', right: 'Exposition' }, { left: 'He tried to fit in by copying others', right: 'Rising Action' }, { left: 'He decided to share his Indigenous heritage', right: 'Climax' }, { left: 'The class was amazed', right: 'Falling Action' }, { left: 'Kai finally felt seen', right: 'Resolution' }] } },
    { id: 'ela-l4-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Choose a story you know well (book, movie, fairy tale) and map it onto the 5-part plot diagram:\n\nStory title:\nExposition (beginning):\nRising Action (problems build):\nClimax (turning point):\nFalling Action (settling):\nResolution (ending):', minLength: 40, rubricHint: 'Names all 5 plot parts. Correctly maps story events to each part. Shows understanding of how tension builds and resolves.' } },
    { id: 'ela-l4-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Using Kai\'s story, explain how NARRATIVE STRUCTURE helps communicate the theme. How does moving from exposition to resolution help the reader understand the message?', minLength: 30, rubricHint: 'Names at least 3 plot parts. Connects structure to theme. Uses specific details from the story.' } },
  ];

  for (const b of l4Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L4, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }

  const l4Questions = [
    { id: 'ela-l4-q1', questionText: 'The CLIMAX of a story is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'The beginning of the story', value: 'a' }, { label: 'The turning point or moment of greatest tension', value: 'b', correct: true }, { label: 'The ending', value: 'c' }, { label: 'A description of the setting', value: 'd' }], correctAnswer: 'b', explanation: 'The climax is the turning point -- the most intense moment where the main conflict reaches its peak.', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l4-q2', questionText: 'Which plot element introduces the characters and setting?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Rising Action', value: 'a' }, { label: 'Exposition', value: 'b', correct: true }, { label: 'Climax', value: 'c' }, { label: 'Resolution', value: 'd' }], correctAnswer: 'b', explanation: 'The exposition is the beginning of the story where we meet the characters, learn the setting, and understand the starting situation.', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l4-q3', questionText: '"He decided to share his Indigenous heritage." This sentence contains a PROPER ADJECTIVE. Which word is it?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'decided', value: 'a' }, { label: 'share', value: 'b' }, { label: 'Indigenous', value: 'c', correct: true }, { label: 'heritage', value: 'd' }], correctAnswer: 'c', explanation: '"Indigenous" is a proper adjective -- it is derived from a proper noun and is capitalized. It describes the type of heritage.', outcomeCode: 'ELA.6.4', difficulty: 2 },
    { id: 'ela-l4-q4', questionText: 'What comes AFTER the climax in a plot diagram?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Exposition', value: 'a' }, { label: 'Rising Action', value: 'b' }, { label: 'Falling Action', value: 'c', correct: true }, { label: 'Conflict', value: 'd' }], correctAnswer: 'c', explanation: 'After the climax (turning point), the falling action shows how the conflict begins to resolve before the resolution.', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l4-q5', questionText: '"Kai finally felt seen." The word "finally" is what part of speech?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Adjective', value: 'a' }, { label: 'Adverb', value: 'b', correct: true }, { label: 'Noun', value: 'c' }, { label: 'Verb', value: 'd' }], correctAnswer: 'b', explanation: '"Finally" is an adverb -- it modifies the verb "felt" by telling us WHEN he felt seen. Adverbs often end in -ly.', outcomeCode: 'ELA.6.4', difficulty: 2 },
    { id: 'ela-l4-q6', questionText: 'During RISING ACTION, the story\'s tension usually:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Decreases', value: 'a' }, { label: 'Stays the same', value: 'b' }, { label: 'Increases', value: 'c', correct: true }, { label: 'Disappears completely', value: 'd' }], correctAnswer: 'c', explanation: 'Rising action is where tension INCREASES through events and complications that build toward the climax.', outcomeCode: 'ELA.6.3', difficulty: 1 },
    { id: 'ela-l4-q7', questionText: 'Which sentence uses a COMMA correctly?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'He shared, his heritage at school.', value: 'a' }, { label: 'When a class project asked him to present his culture, he almost lied.', value: 'b', correct: true }, { label: 'The class was, amazed by his presentation.', value: 'c' }, { label: 'Kai finally, felt seen.', value: 'd' }], correctAnswer: 'b', explanation: 'A comma after an introductory clause ("When a class project asked him to present his culture") is correct. The other options incorrectly split subjects from verbs.', outcomeCode: 'ELA.6.4', difficulty: 2 },
    { id: 'ela-l4-q8', questionText: 'The RESOLUTION of a story shows:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'The moment of greatest tension', value: 'a' }, { label: 'How the story wraps up and what has changed', value: 'b', correct: true }, { label: 'The introduction of new characters', value: 'c' }, { label: 'The setting of the story', value: 'd' }], correctAnswer: 'b', explanation: 'The resolution is the final part where loose ends are tied up and we see what has changed as a result of the story events.', outcomeCode: 'ELA.6.3', difficulty: 1 },
  ];

  for (const q of l4Questions) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L4, questionText: q.questionText, questionType: q.questionType, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L4: ' + l4Blocks.length + ' blocks, ' + l4Questions.length + ' questions');

  // LESSON 5: Drafting My Narrative
  const L5 = 'g6-ela-u1-l5';
  await prisma.lesson.update({ where: { id: L5 }, data: {
    subjectMode: 'ELA', externalUrl: null, estimatedMinutes: 45,
    learningGoal: 'Plan and begin drafting a personal identity narrative. Use the plot diagram and writing craft techniques including show-don\'t-tell.',
    successCriteria: 'I can plan a narrative using a plot diagram.\nI can use show-don\'t-tell to create vivid writing.\nI can draft an opening paragraph that hooks the reader.',
    materials: 'Notebook, pencil, plot diagram from Lesson 4',
    reflectionPrompt: 'What part of drafting was easiest for you? What was hardest? Why?',
    warmUpConfig: { type: 'constructed_response', prompt: 'Think about a moment in your life that shaped who you are today.\n\nBriefly describe what happened in 2-3 sentences. This could become your narrative topic.' },
    masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false },
  }});
  await prisma.lessonBlock.deleteMany({ where: { lessonId: L5 } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: L5 } });

  const l5Blocks = [
    { id: 'ela-l5-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Writing Craft: Show, Don\'t Tell</h3><p>Strong narrative writing <strong>shows</strong> rather than <strong>tells</strong>. Compare:</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0"><div style="background:#fee2e2;padding:12px;border-radius:8px"><strong>Telling:</strong> "I was nervous."</div><div style="background:#dcfce7;padding:12px;border-radius:8px"><strong>Showing:</strong> "My hands trembled as I gripped the edges of my paper. My voice came out in a whisper."</div><div style="background:#fee2e2;padding:12px;border-radius:8px"><strong>Telling:</strong> "She was sad."</div><div style="background:#dcfce7;padding:12px;border-radius:8px"><strong>Showing:</strong> "Her eyes stung and she blinked hard, staring at the ceiling so the tears would stay inside."</div></div><p>Showing uses <strong>sensory details</strong> (sight, sound, touch, taste, smell) and <strong>actions</strong> to let the reader experience the emotion.</p>' } },
    { id: 'ela-l5-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Narrative Opening Hooks</h3><p>A strong opening grabs the reader. Try one of these techniques:</p><ul><li><strong>Action:</strong> Start in the middle of something happening. "I froze when I heard my name called."</li><li><strong>Dialogue:</strong> Start with someone speaking. "\'You are going to love it here,\' my mom said. I was not so sure."</li><li><strong>Question:</strong> Ask something intriguing. "Have you ever wished you could be someone else, even for a day?"</li><li><strong>Sensory Detail:</strong> Paint a picture. "The smell of cardamom and ginger filled the kitchen every Sunday morning."</li></ul>' } },
    { id: 'ela-l5-learn-3', section: 'LEARN', blockType: 'VOCABULARY', order: 3, content: { terms: [{ term: 'Show, Don\'t Tell', definition: 'A writing technique where you use actions, dialogue, and sensory details instead of directly stating emotions.', example: 'Instead of "I was scared," write "My heart hammered and I pressed myself against the cold wall."' }, { term: 'Sensory Details', definition: 'Words and phrases that appeal to the five senses (sight, sound, touch, taste, smell).', example: '"The warm bread crackled as I tore it apart."' }, { term: 'Hook', definition: 'The opening of a story designed to grab the reader\'s attention immediately.', example: '"I never thought a single word could change everything."' }, { term: 'Voice', definition: 'The unique personality and style that comes through in a writer\'s words.', example: 'Your voice is what makes your writing sound like YOU.' }] } },
    { id: 'ela-l5-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Plan your identity narrative using the plot diagram:\n\n1. EXPOSITION -- Who are you? What is the setting? What was "normal" before?\n2. RISING ACTION -- What happened? What problem or change occurred?\n3. CLIMAX -- What was the turning point or most important moment?\n4. FALLING ACTION -- What happened next? How did things start to settle?\n5. RESOLUTION -- How did the experience shape who you are today?', minLength: 50, rubricHint: 'Completes all 5 parts. Events connect logically. Shows personal reflection.' } },
    { id: 'ela-l5-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Write your OPENING PARAGRAPH (4-6 sentences). Use one of the hook techniques (action, dialogue, question, or sensory detail) to grab the reader.\n\nRemember: SHOW, don\'t tell. Use sensory details and specific actions instead of just stating your feelings.', minLength: 40, rubricHint: 'Uses a hook technique. Shows rather than tells. Includes sensory details. Writing has voice.' } },
    { id: 'ela-l5-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Look back at your draft opening.\n\n1. Did you use show-don\'t-tell? Find one sentence where you showed instead of told.\n2. What part of drafting was easiest? What was hardest? Why?\n3. What is one thing you want to improve in your next draft?', minLength: 30, rubricHint: 'Identifies show-don\'t-tell usage. Reflects honestly on writing process. Sets a specific revision goal.' } },
  ];

  for (const b of l5Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L5, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }

  const l5Questions = [
    { id: 'ela-l5-q1', questionText: 'Which sentence SHOWS rather than tells?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'I was really nervous.', value: 'a' }, { label: 'My hands trembled and my voice cracked as I stepped to the front.', value: 'b', correct: true }, { label: 'The presentation was scary.', value: 'c' }, { label: 'I felt bad about it.', value: 'd' }], correctAnswer: 'b', explanation: 'Option B uses physical actions ("hands trembled," "voice cracked") and sensory details to SHOW nervousness instead of just stating it.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l5-q2', questionText: '"The smell of cardamom and ginger filled the kitchen." This sentence appeals to which SENSE?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Sight', value: 'a' }, { label: 'Smell', value: 'b', correct: true }, { label: 'Touch', value: 'c' }, { label: 'Hearing', value: 'd' }], correctAnswer: 'b', explanation: '"Smell of cardamom and ginger" directly references the sense of smell with specific, vivid details.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l5-q3', questionText: 'A narrative HOOK is designed to:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Summarize the entire story', value: 'a' }, { label: 'Grab the reader\'s attention immediately', value: 'b', correct: true }, { label: 'Introduce all the characters', value: 'c' }, { label: 'State the theme directly', value: 'd' }], correctAnswer: 'b', explanation: 'A hook is the very first line or lines of your story -- its job is to make the reader want to keep reading.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l5-q4', questionText: '"\'You are going to love it here,\' my mom said." This opening uses which hook technique?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Action', value: 'a' }, { label: 'Dialogue', value: 'b', correct: true }, { label: 'Question', value: 'c' }, { label: 'Sensory detail', value: 'd' }], correctAnswer: 'b', explanation: 'This opening starts with a character speaking -- that is a dialogue hook. The quotation marks show someone is talking.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l5-q5', questionText: 'Which COMMA rule applies in: "When I heard my name, I froze"?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Comma between items in a list', value: 'a' }, { label: 'Comma after an introductory clause', value: 'b', correct: true }, { label: 'Comma before a conjunction', value: 'c' }, { label: 'Comma in a date', value: 'd' }], correctAnswer: 'b', explanation: '"When I heard my name" is an introductory dependent clause. A comma separates it from the main clause "I froze."', outcomeCode: 'ELA.6.4', difficulty: 2 },
    { id: 'ela-l5-q6', questionText: '"My heart hammered." The word "hammered" is an example of:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A simile', value: 'a' }, { label: 'Personification -- giving a human action to a non-human thing', value: 'b', correct: true }, { label: 'Alliteration', value: 'c' }, { label: 'A fact', value: 'd' }], correctAnswer: 'b', explanation: 'Hearts do not literally hammer -- this gives a human action (hammering) to a body part, making it personification. It vividly shows fear or excitement.', outcomeCode: 'ELA.6.4', difficulty: 2 },
    { id: 'ela-l5-q7', questionText: 'In narrative writing, VOICE refers to:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'How loud you read', value: 'a' }, { label: 'The unique personality and style that comes through in your words', value: 'b', correct: true }, { label: 'The volume of the story', value: 'c' }, { label: 'Whether you use first or third person', value: 'd' }], correctAnswer: 'b', explanation: 'Voice is your unique writing personality -- the way YOU put words together that makes your writing distinctly yours.', outcomeCode: 'ELA.6.4', difficulty: 1 },
    { id: 'ela-l5-q8', questionText: 'Which sentence uses QUOTATION MARKS correctly for dialogue?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'She said "I am going home."', value: 'a' }, { label: '"I am going home," she said.', value: 'b', correct: true }, { label: 'She said, I am going home.', value: 'c' }, { label: '"I am going home, she said."', value: 'd' }], correctAnswer: 'b', explanation: 'Correct dialogue format: quotation marks around the spoken words, comma inside the quotes before the dialogue tag ("she said").', outcomeCode: 'ELA.6.4', difficulty: 2 },
  ];

  for (const q of l5Questions) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L5, questionText: q.questionText, questionType: q.questionType, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L5: ' + l5Blocks.length + ' blocks, ' + l5Questions.length + ' questions');

  console.log('\nELA Unit 1 Lessons 3-5 seeded!');
}

main()
  .catch((e) => { console.error('Seed failed:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
